apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: flux-system
spec: {}
status: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://fluxcd-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flux
        namespace: flux-system
      version: 2.x.x
  interval: 1m0s

